apiVersion: v2
name: odk-central-pyxform
description: A Helm chart for odk-central-pyxform.
type: application
version: v2025.2.1
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
keywords:
  - odk
  - odk-central
  - odk-central-pyxform
