apiVersion: v2
name: mock-identity-system
description: A Helm chart for MOSIP Mock Identity System module
type: application
version: 0.9.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
  condition: postgresql.enabled
- name: softhsm
  repository: https://mosip.github.io/mosip-helm
  version: 12.0.1-B2
  condition: softhsm.enabled
- name: artifactory
  repository: https://openg2p.github.io/openg2p-helm
  version: 12.0.2
  condition: artifactory.enabled
home: https://mosip.io
keywords:
  - mosip
  - esignet
  - mock-identity-system
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "Mock Identity System"
