#!/usr/bin/env bash
# =============================================================================
# Environment — Phase 2: commons install (runs ON THE LAPTOP)
# =============================================================================
# Steps:
#   E2.1  Resolve env values (re-uses helpers from phase1.sh)
#   E2.2  Generate transient env-config.yaml in .state/environment/
#         with external-PG extras (postgresql.enabled=false, host, secret)
#         and per-service hostname overrides if set
#   E2.3  Invoke automation/environment/env-cluster.sh --step 4 (commons-base)
#   E2.4  Invoke automation/environment/env-cluster.sh --step 5 (commons-services)
#
# Gated by environment.install_commons in prod-config (default true).
# When false, the entire phase is skipped — phase 1 (gateway, repo) is
# enough on its own and commons can be installed later via Rancher UI.
# =============================================================================

ENV_CLUSTER_SH="${WORK_DIR}/../environment/env-cluster.sh"

# ---------------------------------------------------------------------------
# E2.1 — re-resolve the values phase1 set up; needed when phase2 is run
# standalone via --role environment --phase 2.
# ---------------------------------------------------------------------------
phase2_resolve_values() {
    # Re-use phase1's helper so we resolve consistently.
    source "${SCRIPT_DIR}/phase1.sh"
    env_resolve_values

    if [[ ! -f "$KUBECONFIG_CACHE" ]]; then
        log_error "Kubeconfig cache missing at ${KUBECONFIG_CACHE}" \
                  "Phase 1 must complete before phase 2 can run" \
                  "Run: ./openg2p-prod.sh --role environment --phase 1 --config <your-config>"
        exit 1
    fi
    export KUBECONFIG="$KUBECONFIG_CACHE"

    COMMONS_VERSION=$(cfg "environment.commons_version" "0.0.0-develop")
    ENV_ADMIN_EMAIL=$(cfg "environment.admin_email" "")

    # commons-base service-UI hostnames (override keys live in commons-base
    # questions.yaml; blank → <service>.<base_domain>).
    ENV_KAFKA_HOST=$(cfg "environment.kafka_hostname" "")
    ENV_MINIO_HOST=$(cfg "environment.minio_hostname" "")

    # commons-services hostnames (override keys live in commons-services
    # questions.yaml; blank → <service>.<base_domain>).
    ENV_SUPERSET_HOST=$(cfg "environment.superset_hostname" "")
    ENV_ODK_HOST=$(cfg "environment.odk_hostname" "")
    ENV_IAM_HOST=$(cfg "environment.iam_hostname" "")
    ENV_STAFF_PORTAL_HOST=$(cfg "environment.staff_portal_hostname" "")
    ENV_STAFF_PORTAL_API_HOST=$(cfg "environment.staff_portal_api_hostname" "")
}

# ---------------------------------------------------------------------------
# E2.2 — generate the transient env-config.yaml that env-cluster.sh consumes.
#
# extra_helm_args:
#   * postgresql.enabled=false             — disable in-cluster Bitnami PG
#   * global.postgresqlHost=<storage_priv> — point at storage node's host PG
#   * global.postgresqlSecret=<name>       — secret created in phase 1
#   * global.kafkaUiHostname / global.minioHostname — if customer overrides
# ---------------------------------------------------------------------------
phase2_generate_env_config() {
    log_step "E2.2" "Generating transient env-config.yaml"

    local out="${STATE_DIR}/environment/env-config.yaml"
    mkdir -p "$(dirname "$out")"

    # External-PG extras shared by both charts. env-cluster.sh's step4/step5
    # set defaults first; our extras are appended LAST so our --set values win
    # (helm flag precedence = last-wins).
    local pg_extras="--set postgresql.enabled=false"
    pg_extras+=" --set global.postgresqlHost=${STORAGE_PRIV}"
    pg_extras+=" --set global.postgresqlSecret=${PG_SECRET_NAME}"
    pg_extras+=" --set global.postgresqlSecretKey=postgres-password"

    # commons-base extras: external PG + base service-UI hostname overrides.
    local base_extras="$pg_extras"
    [[ -n "$ENV_KAFKA_HOST" ]] && base_extras+=" --set global.kafkaUiHostname=${ENV_KAFKA_HOST}"
    [[ -n "$ENV_MINIO_HOST" ]] && base_extras+=" --set global.minioHostname=${ENV_MINIO_HOST}"

    # commons-services extras: external PG + services hostname overrides.
    local svc_extras="$pg_extras"
    [[ -n "$ENV_SUPERSET_HOST" ]]         && svc_extras+=" --set global.supersetHostname=${ENV_SUPERSET_HOST}"
    [[ -n "$ENV_ODK_HOST" ]]              && svc_extras+=" --set global.odkHostname=${ENV_ODK_HOST}"
    [[ -n "$ENV_IAM_HOST" ]]              && svc_extras+=" --set global.iamHostname=${ENV_IAM_HOST}"
    [[ -n "$ENV_STAFF_PORTAL_HOST" ]]     && svc_extras+=" --set global.staffPortalHostname=${ENV_STAFF_PORTAL_HOST}"
    [[ -n "$ENV_STAFF_PORTAL_API_HOST" ]] && svc_extras+=" --set global.staffPortalApiHostname=${ENV_STAFF_PORTAL_API_HOST}"

    cat > "$out" <<YAML
# AUTO-GENERATED by openg2p-prod.sh — do not hand-edit. Regenerated on each
# --role environment run from prod-config.yaml.
environment: "${ENV_NAME}"
base_domain: "${ENV_BASE_DOMAIN}"
admin_email: "${ENV_ADMIN_EMAIL}"

commons_base:
  chart_name:    "openg2p-commons-base"
  chart_path:    ""
  chart_repo:    "https://openg2p.github.io/openg2p-helm"
  chart_version: "${COMMONS_VERSION}"
  extra_helm_args: "${base_extras}"

commons_services:
  chart_name:    "openg2p-commons-services"
  chart_path:    ""
  chart_repo:    "https://openg2p.github.io/openg2p-helm"
  chart_version: "${COMMONS_VERSION}"
  extra_helm_args: "${svc_extras}"

modules:
  commons: true
YAML
    chmod 0600 "$out"
    log_success "Transient env-config.yaml written: ${out}"
    GENERATED_ENV_CONFIG="$out"
}

# ---------------------------------------------------------------------------
# E2.3 / E2.4 — invoke env-cluster.sh's step 4 and step 5
# ---------------------------------------------------------------------------
phase2_invoke_env_cluster() {
    if [[ ! -x "$ENV_CLUSTER_SH" ]]; then
        log_error "env-cluster.sh not found or not executable at: ${ENV_CLUSTER_SH}" \
                  "Expected the environment automation alongside production automation" \
                  "Verify automation/environment/env-cluster.sh exists in the repo"
        exit 1
    fi

    # env-cluster.sh handles its own idempotency for steps 4/5 (helm upgrade
    # --install). KUBECONFIG is exported by phase2_resolve_values.

    log_step "E2.3" "Installing openg2p-commons-base (chart version ${COMMONS_VERSION})"
    if [[ "$FORCE_MODE" == "true" ]]; then
        "$ENV_CLUSTER_SH" --config "$GENERATED_ENV_CONFIG" --step 4 --force
    else
        "$ENV_CLUSTER_SH" --config "$GENERATED_ENV_CONFIG" --step 4
    fi

    log_step "E2.4" "Installing openg2p-commons-services (chart version ${COMMONS_VERSION})"
    if [[ "$FORCE_MODE" == "true" ]]; then
        "$ENV_CLUSTER_SH" --config "$GENERATED_ENV_CONFIG" --step 5 --force
    else
        "$ENV_CLUSTER_SH" --config "$GENERATED_ENV_CONFIG" --step 5
    fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
phase2_main() {
    phase2_resolve_values

    if [[ "$INSTALL_ENV" != "true" ]]; then
        log_warn "install_environment=false — skipping environment phase 2."
        return 0
    fi

    if [[ "$INSTALL_COMMONS" != "true" ]]; then
        log_warn "environment.install_commons=false — skipping commons install."
        log_warn "Scaffolding (namespace, project, gateway, PG secret) is still in place."
        log_warn "Install commons-base + commons-services via the Rancher UI when ready."
        return 0
    fi

    log_step "ENV phase 2" "Commons install into '${ENV_NAME}' (external PG at ${STORAGE_PRIV})"

    phase2_generate_env_config
    phase2_invoke_env_cluster

    log_success "ENV phase 2 complete. commons-base + commons-services installed."
    echo ""
    log_info "Service URLs:"
    log_info "  MinIO:        https://${ENV_MINIO_HOST:-minio.${ENV_BASE_DOMAIN}}"
    log_info "  Kafka UI:     https://${ENV_KAFKA_HOST:-kafka.${ENV_BASE_DOMAIN}}"
    log_info "  Superset:     https://${ENV_SUPERSET_HOST:-superset.${ENV_BASE_DOMAIN}}"
    log_info "  ODK Central:  https://${ENV_ODK_HOST:-odk.${ENV_BASE_DOMAIN}}"
    log_info "  Staff Portal: https://${ENV_STAFF_PORTAL_HOST:-staff-portal.${ENV_BASE_DOMAIN}}"
    log_info "  eSignet:      https://esignet.${ENV_BASE_DOMAIN}   (derived from base domain)"
}
