_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        description: "Authenticate via HTTP Basic against internal users database"
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        description: "Authenticate via Keycloak OIDC"
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: groups
            openid_connect_url: ${KEYCLOAK_ISSUER_URL}/.well-known/openid-configuration
        authentication_backend:
          type: noop
      kerberos_auth_domain:
        http_enabled: false
        transport_enabled: false
      proxy_auth_domain:
        http_enabled: false
        transport_enabled: false
      jwt_auth_domain:
        http_enabled: false
        transport_enabled: false
      clientcert_auth_domain:
        http_enabled: false
        transport_enabled: false
      ldap:
        http_enabled: false
        transport_enabled: false
    authz: {}
