dashboards:
  enabled: true
  replicaCount: 1

  extraVolumes:
  - name: dashboards-config
    configMap:
      name: opensearch-conf-files

  extraVolumeMounts:
  - name: dashboards-config
    mountPath: /opt/bitnami/opensearch-dashboards/config.default/opensearch_dashboards.yml
    subPath: opensearch_dashboards.yml

master:
  replicaCount: 1
  persistence:
    size: 8Gi
  heapSize: 256m
  masterOnly: false

data:
  replicaCount: 0
  # persistence:
  #   size: 8Gi

coordinating:
  replicaCount: 0

ingest:
  replicaCount: 0

extraVolumes:
- name: security-config
  configMap:
    name: opensearch-conf-files

extraVolumeMounts:
- name: security-config
  mountPath: /opt/bitnami/opensearch/config.default/opensearch-security/config.yml
  subPath: opensearch-security-config.yml

security:
  enabled: true
  tls:
    restEncryption: true
