apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-node-memory-usage-high
  namespace: cattle-monitoring-system
spec:
  groups:
    - name: node-memory
      rules:
        - alert: NodeMemoryUsageHigh
          annotations:
            description: >-
              Node {{ $labels.instance }} memory usage is above 80% for more than 5 minutes.
              Current usage: {{ $value | humanizePercentage }}.
            runbook_url: >-
              https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodememoryusagehigh
            summary: High memory usage on node {{ $labels.instance }}.
          expr: >-
            1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) > 0.80
          for: 300s
          labels:
            severity: critical
