apiVersion: v2
name: odoo
description: A Helm chart for Odoo
type: application
version: 1.2.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
  condition: postgresql.enabled
keywords:
  - odoo
