{{- if .Values.springCloudConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-config-server-git-secret
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $k, $v := .Values.springCloudConfig.gitRepo }}
  {{ $k }}: {{ include "common.tplvalues.render" (dict "value" $v "context" $) | b64enc | quote }}
  {{- end }}
{{- end }}
