global:
  hostname: gctb.openg2p.sandbox.net

envVars:
  GCTB_CORE_DB_HOSTNAME: "postgres-postgresql.postgres"
  GCTB_CORE_DEFAULT_ID_TOKEN_VERIFY_AT_HASH: "false"
  GCTB_CORE_MULTIPLEX_FA_BACKEND_MAPPING: '[{"order":1,"regex":"(mpesa)$","name":"mpesa"}, {"order":2, "regex": "(bank_acc|wallet)$", "name":"mojaloop"}]'

envVarsFrom:
  GCTB_CORE_DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: postgres-postgresql
        key: password

postgresql:
  enabled: false
