apiVersion: v2
name: odk-central-enketo
description: A Helm chart for odk-central-enketo.
type: application
version: v2024.2.1
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
keywords:
  - odk
  - odk-central
  - odk-central-enketo
