hostname: ""
supportEmail: 'support@{{ tpl .Values.hostname $ | default "openg2p.org" }}'

replicaCount: 1

service:
  type: ClusterIP
  port: 80

image:
  registry: ghcr.io
  repository: enketo/enketo
  tag: 7.5.1
  pullPolicy: IfNotPresent

containerPort: 8005

startupProbe:
  enabled: true
  httpGet:
    port: http
    path: /
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1

livenessProbe:
  enabled: true
  httpGet:
    port: http
    path: /
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    port: http
    path: /
  initialDelaySeconds: 0
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

command: []
args: []

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 1500Mi

containerSecurityContext:
  enabled: false
  runAsUser: odk
  runAsNonRoot: true

podSecurityContext:
  enabled: false
  fsGroup: 1001

enketoSrcDir: /srv/src/enketo/packages/enketo-express

# Leave the following secrets blank to generate during installation.
# If you already have existing values, they can be passed here.
enketoSecret: ""
enketoLessSecret: ""
enketoApiKey: ""

envVars:
  DOMAIN: '{{ tpl .Values.hostname $ }}'
  SUPPORT_EMAIL: '{{ tpl .Values.supportEmail $ }}'
  ENKETO_PORT: "8005"
  ENKETO_SRC_DIR: '{{ include "common.tplvalues.render" (dict "value" .Values.enketoSrcDir "context" $) }}'
  REDIS_MAIN_HOST: '{{ tpl .Values.redisMainInstallationName $ }}'
  REDIS_CACHE_HOST: '{{ tpl .Values.redisCacheInstallationName $ }}'
envVarsFrom:
  ENKETO_SECRET:
    secretKeyRef:
      name: '{{ include "common.names.fullname" . }}'
      key: enketo-secret
  ENKETO_LESS_SECRET:
    secretKeyRef:
      name: '{{ include "common.names.fullname" . }}'
      key: enketo-less-secret
  ENKETO_API_KEY:
    secretKeyRef:
      name: '{{ include "common.names.fullname" . }}'
      key: enketo-api-key

startEnketoScript: |-
  #!/bin/sh

  set -o pipefail
  set -e

  CONFIG_PATH=${ENKETO_SRC_DIR}/config/config.json
  echo "generating enketo configuration..."

  envsubst < "$CONFIG_PATH.template" > "$CONFIG_PATH"

  echo "starting enketo..."
  cd $ENKETO_SRC_DIR
  exec yarn workspace enketo-express start

configJsonTemplate: |-
  {
    "app name": "Enketo",
    "base path": "-",
    "encryption key": "${ENKETO_SECRET}",
    "id length": 31,
    "less secure encryption key": "${ENKETO_LESS_SECRET}",
    "linked form and data server": {
        "api key": "${ENKETO_API_KEY}",
        "authentication": {
          "type": "cookie",
          "url": "https://${DOMAIN}/#/login?next={RETURNURL}"
        },
        "name": "ODK Central",
        "server url": "${DOMAIN}"
    },
    "logo": {
      "source": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=",
      "href": ""
    },
    "offline enabled": true,
    "payload limit": "1mb",
    "port": "${ENKETO_PORT}",
    "query parameter to pass to submission": "st",
    "redis": {
      "main": {
        "host": "${REDIS_MAIN_HOST}",
        "port": "6379"
      },
      "cache": {
        "host": "${REDIS_CACHE_HOST}",
        "port": "6379"
      }
    },
    "support": {
      "email": "${SUPPORT_EMAIL}"
    },
    "text field character limit": 1000000,
    "exclude non-relevant": true
  }

redisMainInstallationName: '{{ include "common.names.fullname" . }}-redis-main-master'
redisCacheInstallationName: '{{ include "common.names.fullname" . }}-redis-cache-master'
