apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
data:
  config.json.template: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.configJsonTemplate "context" $) | nindent 4 }}
  start-odk.sh: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.startOdkScript "context" $) | nindent 4 }}
