{{- if eq .Values.keystoreType "PKCS12" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  p12-keystore-pass: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "p12-keystore-pass" "length" 16 "providedValues" (list "p12KeystorePass") "context" $) }}
{{- end }}
