{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  hosts:
  - {{ default .Values.global.keymanagerHostname .Values.istio.virtualservice.host | quote }}
  gateways:
  - {{ default (include "common.names.fullname" .) .Values.istio.virtualservice.gateway }}
  http:
  - headers:
      request:
        set:
          x-forwarded-host: {{ default .Values.global.keymanagerHostname .Values.istio.virtualservice.host | quote }}
          x-forwarded-proto: https
    route:
    - destination:
        host: {{ tpl .Values.istio.virtualservice.destination $ }}
        port:
          number: {{ tpl .Values.istio.virtualservice.destinationPort $ }}
{{- end }}
{{- end }}
