{{- if .Values.istio.enabled  }}
{{- if .Values.istio.gateway.enabled  }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{ toYaml .Values.istio.gateway.ingressController | nindent 4 }}
  servers:
  {{- if .Values.istio.gateway.httpEnabled }}
  - port:
      name: http2
      number: 8080
      protocol: HTTP2
    hosts:
      - {{- include "odoo.hostname" .Values.istio.gateway }}
    {{- if .Values.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- end }}
  {{- if .Values.istio.gateway.httpsEnabled }}
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
      - {{- include "odoo.hostname" .Values.istio.gateway }}
    tls:
      {{ toYaml (omit .Values.istio.gateway.tls "enabled") | nindent 6 }}
  {{- end }}
  {{- if .Values.istio.gateway.extraServers }}
  {{- include "common.tplvalues.render" (dict "value" .Values.istio.gateway.extraServers "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
