{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  hosts:
  - {{- include "odoo.hostname" .Values.istio.virtualservice }}
  gateways:
    - {{ default .Values.istio.virtualservice.gateway (include "common.names.fullname" .) }}
  http:
  {{- if .Values.istio.virtualservice.redirectRootToWeb }}
  - match:
    - uri:
        exact: /
    redirect:
      uri: /web
  {{- end }}
  - headers:
      request:
        set:
          x-forwarded-host: {{- include "odoo.hostname" .Values.istio.virtualservice }}
          x-forwarded-proto: https
    route:
    - destination:
        host: {{ template "common.names.fullname" . }}
        port:
          number: {{ .Values.odoo.service.port }}
  {{- if .Values.istio.virtualservice.extraRoutes }}
  {{- include "common.tplvalues.render" (dict "value" .Values.istio.virtualservice.extraRoutes "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}