apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: rancher
spec:
  selector:
    istio-rancher: ingressgateway
  servers:
  - hosts:
    - ${RANCHER_HOSTNAME}
    port:
      name: http-redirect-https
      number: 81
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - ${RANCHER_HOSTNAME}
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rancher
spec:
  gateways:
  - rancher
  hosts:
  - ${RANCHER_HOSTNAME}
  http:
  - route:
    - destination:
        host: rancher
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https
