apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: rancher
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    pathNormalization:
      normalization: MERGE_SLASHES
    defaultConfig:
      proxyMetadata:
        ISTIO_META_IDLE_TIMEOUT: 0s
      holdApplicationUntilProxyStarts: true
  components:
    base:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    - name: istio-ingressgateway-rancher
      enabled: true
      label:
        istio: ingressgateway-rancher
        istio-rancher: ingressgateway
      k8s:
        hpaSpec:
          minReplicas: 2
        nodeSelector:
          shouldInstallIstioIngress: "true"
        service:
          type: NodePort
          ports:
          - name: tcp-status-port
            port: 15021
            nodePort: 30521
          - name: http2
            port: 80
            targetPort: 8080
            nodePort: 30080
          - name: http2-redirect-https
            port: 81
            targetPort: 8081
            nodePort: 30081
