apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: nfs-csi
parameters:
  mountPermissions: "0777"
  server: ${NFS_SERVER}
  share: ${NFS_PATH}
  subDir: '${pvc.metadata.namespace}-${pvc.metadata.name}-${pv.metadata.name}'
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
