apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: primary
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    pathNormalization:
      normalization: MERGE_SLASHES
    defaultConfig:
      proxyMetadata:
        ISTIO_META_IDLE_TIMEOUT: 0s
      holdApplicationUntilProxyStarts: true
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        nodeSelector:
          shouldInstallIstioIngress: "true"
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: kind
            value: DaemonSet
          - path: spec.strategy
            value:
          - path: spec.updateStrategy
            value:
              rollingUpdate:
                maxUnavailable: 1
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8080].hostPort
            value: 80
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8443].hostPort
            value: 443
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:5432].hostPort
            value: 5432
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:5433].hostPort
            value: 5433
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:5434].hostPort
            value: 5434
        service:
          type: ClusterIP
          ports:
          - port: 15021
            name: status-port
            targetPort: 15021
            protocol: TCP
          - port: 443
            targetPort: 8443
            name: https
          - port: 80
            targetPort: 8080
            name: http2
          - port: 5432
            targetPort: 5432
            name: tcp-postgres01
          - port: 5433
            targetPort: 5433
            name: tcp-postgres02
          - port: 5434
            targetPort: 5434
            name: tcp-postgres03
