#!/usr/bin/env bash
# =============================================================================
# Reverse Proxy Node — Phase 1
# =============================================================================
# Single-NIC layout:
#   • rp_public_ip   → Wireguard UDP endpoint (the public/reachable address).
#                      On AWS this is the EIP NAT'd to the ENI; on-prem it's
#                      either a public IP or whatever address the admin uses
#                      to reach the WG server.
#   • rp_private_ip  → The ENI's actual bound IP on this host. Admin Nginx
#                      server blocks bind here. WG-decapsulated traffic from
#                      admin laptops is delivered here.
#
# Channel separation is enforced by the SG / network firewall (only 22 and the
# WG port are reachable from the internet), NOT by physical NIC separation.
#
# Steps:
#   R1.1  apt basics
#   R1.2  Verify rp_private_ip is bound to a local NIC
#   R1.3  ufw — SSH from admin_cidr, WG/UDP from anywhere, trust private/WG subnets
#   R1.4  IP forwarding + Wireguard server + N peer configs (+ optional DNS push)
#   R1.5  Customer cert ingest + validate + install to /etc/openg2p/certs/public/
#   R1.6  Nginx — server blocks per admin hostname, bound to rp_private_ip:443
#
# Customer-supplied (NOT generated by this script):
#   • DNS A-records (admin hostnames rancher/keycloak → rp_private_ip)
#   • TLS certificates (one wildcard OR per-FQDN)
#
# Docs:
#   https://docs.openg2p.org/operations/deployment/automation/three-node-automation#prerequisites
# =============================================================================

# Paths
CERTS_DIR="/etc/openg2p/certs/public"
PEER_DIR="/etc/wireguard/peers"
STAGED_CERTS_DIR="${WORK_DIR}/certs"      # populated by ssh_stage_role

DOCS_URL_BASE="https://docs.openg2p.org/operations/deployment/automation/three-node-automation"

# ─────────────────────────────────────────────────────────────────────────
# Helpers — resolve admin hostnames from config (auto-derive from public_domain
# when per-service field is blank)
# ─────────────────────────────────────────────────────────────────────────
rp_hostname() {
    local service="$1"   # rancher | keycloak
    local explicit
    explicit=$(cfg "${service}_hostname")
    if [[ -n "$explicit" ]]; then
        echo "$explicit"
    else
        local domain
        domain=$(cfg "public_domain")
        if [[ -z "$domain" ]]; then
            log_error "Hostname for ${service} cannot be derived" \
                      "Both ${service}_hostname and public_domain are blank in prod-config.yaml" \
                      "Set public_domain (e.g. openg2p.gov.eth) or set ${service}_hostname explicitly" \
                      "" \
                      "${DOCS_URL_BASE}#id-3.-customer-supplied-dns-records"
            exit 1
        fi
        echo "${service}.${domain}"
    fi
}

# ─────────────────────────────────────────────────────────────────────────
# R1.1  apt basics
# ─────────────────────────────────────────────────────────────────────────
rp_install_basics() {
    local step="rp.phase1.basics"
    if skip_if_done "$step" "apt basics"; then return 0; fi

    log_step "R1.1" "Install apt basics, Wireguard, Nginx"

    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y --no-install-recommends \
        curl wget jq openssl dnsutils ca-certificates \
        ufw \
        wireguard-tools \
        nginx

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.2  Verify rp_private_ip is bound to a local NIC
# ─────────────────────────────────────────────────────────────────────────
# We do NOT check rp_public_ip here. On AWS, rp_public_ip is an Elastic IP
# that AWS NATs to the ENI's private address — the OS never sees the EIP
# itself, so `ip -4 addr` won't show it. On on-prem the public IP may be
# directly bound or may itself be NAT'd by an upstream firewall — either is
# fine. The EIP/public reachability is implicit (SSH from the orchestrator
# already worked, or this script wouldn't be running). We only need to
# ensure the OS-visible private IP is up, since Nginx binds admin server
# blocks to it and the WG-decapsulated traffic is delivered there.
rp_verify_nic() {
    local step="rp.phase1.nic"
    if skip_if_done "$step" "NIC verification"; then return 0; fi

    log_step "R1.2" "Verify rp_private_ip is bound on this host"

    local pub priv
    pub=$(cfg "rp_public_ip")
    priv=$(cfg "rp_private_ip")
    [[ -z "$priv" ]] && priv=$(cfg "rp_internal_ip")   # legacy alias

    if [[ -z "$pub" || -z "$priv" ]]; then
        log_error "rp_public_ip or rp_private_ip not set in config" \
                  "Both fields are required" \
                  "Fill in rp_public_ip (WG endpoint) and rp_private_ip (this host's NIC IP) in prod-config.yaml" \
                  "" \
                  "${DOCS_URL_BASE}#prerequisites"
        exit 1
    fi

    log_info "  rp_public_ip:   ${pub}   (Wireguard endpoint; may be NAT'd / EIP)"

    if ! ip -4 addr 2>/dev/null | grep -q "inet ${priv}/"; then
        log_error "Configured rp_private_ip ${priv} is not bound to any interface on this host" \
                  "The RP needs its primary NIC to have this IP for Nginx + WG-decapsulated traffic" \
                  "Verify the ENI/NIC is attached and the IP is bound (netplan/cloud-init)" \
                  "ip -4 addr; ip route" \
                  "${DOCS_URL_BASE}#prerequisites"
        exit 1
    fi

    log_success "  rp_private_ip bound: ${priv}"
    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.3  ufw
# ─────────────────────────────────────────────────────────────────────────
rp_configure_ufw() {
    local step="rp.phase1.ufw"
    if skip_if_done "$step" "ufw rules"; then return 0; fi

    log_step "R1.3" "Configure ufw — public SSH/WG, internal trusted"

    local admin_cidr=$(cfg "admin_cidr" "0.0.0.0/0")
    local wg_port=$(cfg "wg_port" "51820")
    local wg_subnet=$(cfg "wg_subnet" "10.15.0.0/16")
    local private_subnet=$(cfg "private_subnet")

    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing

    # Public
    ufw allow from "$admin_cidr" to any port 22 proto tcp
    ufw allow "${wg_port}/udp" comment "Wireguard"

    # Trusted networks
    if [[ -n "$private_subnet" ]]; then
        ufw allow from "$private_subnet"
    fi
    ufw allow from "$wg_subnet"

    ufw --force enable

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.4  Wireguard server + peer configs (server listens on the WG UDP port on all interfaces; external reachability is gated by the SG)
# ─────────────────────────────────────────────────────────────────────────
rp_setup_wireguard() {
    local step="rp.phase1.wireguard"
    if skip_if_done "$step" "Wireguard server"; then return 0; fi

    log_step "R1.4" "Configure Wireguard server (listens on the WG UDP port; SG gates external reachability)"

    local rp_pub=$(cfg "rp_public_ip")
    local endpoint=$(cfg "wg_endpoint")
    if [[ -z "$endpoint" ]]; then endpoint="$rp_pub"; fi
    local wg_subnet=$(cfg "wg_subnet" "10.15.0.0/16")
    local wg_port=$(cfg "wg_port" "51820")
    local wg_peers=$(cfg "wg_peers" "8")
    local private_subnet=$(cfg "private_subnet")

    # Enable IP forwarding (peers need to route into the internal subnet)
    sysctl -w net.ipv4.ip_forward=1 > /dev/null
    grep -q '^net.ipv4.ip_forward=1' /etc/sysctl.conf || \
        echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

    # Parse the WG /16 subnet
    local subnet_base=$(echo "$wg_subnet" | cut -d/ -f1)
    local subnet_mask=$(echo "$wg_subnet" | cut -d/ -f2)
    local octet1=$(echo "$subnet_base" | cut -d. -f1)
    local octet2=$(echo "$subnet_base" | cut -d. -f2)

    mkdir -p /etc/wireguard
    chmod 700 /etc/wireguard

    if [[ -f /etc/wireguard/wg0.conf ]] && systemctl is-active --quiet wg-quick@wg0; then
        log_success "Wireguard already configured and running."
        mark_step_done "$step"
        return 0
    fi

    local server_priv server_pub
    server_priv=$(wg genkey)
    server_pub=$(echo "$server_priv" | wg pubkey)

    local server_ip="${octet1}.${octet2}.0.1"

    # MASQUERADE matches by source CIDR (wg_subnet), not by interface name —
    # Ubuntu 24.04 uses predictable names like ens5/enp0s3.
    #
    # FORWARD chain: use -I (insert at top), NOT -A (append). Ubuntu's ufw
    # ships with DEFAULT_FORWARD_POLICY="DROP" and installs a policy-
    # enforcement chain (ufw-reject-forward -> ufw-skip-to-policy-forward) in
    # FORWARD. Appended rules sit AFTER that drop and never match, so traffic
    # from wg0 -> private subnet is silently dropped — the laptop can still
    # hit local services on the RP (INPUT path: admin Nginx terminates on
    # rp_private_ip) but cannot reach compute/storage private IPs (FORWARD
    # path). Inserting at the head of FORWARD makes the ACCEPT match before
    # ufw's drop. PostDown uses -D which matches by rule content (works
    # whether the rule was inserted or appended).
    cat > /etc/wireguard/wg0.conf <<EOF
# OpenG2P Wireguard server — auto-generated by openg2p-prod orchestrator
[Interface]
Address = ${server_ip}/${subnet_mask}
ListenPort = ${wg_port}
PrivateKey = ${server_priv}
PostUp = iptables -I FORWARD 1 -i wg0 -j ACCEPT; iptables -I FORWARD 1 -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s ${wg_subnet} -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s ${wg_subnet} -j MASQUERADE
EOF

    # Peer configs — admin laptops route the WG subnet AND the private subnet
    # through the tunnel, so they can reach admin services on rp_private_ip
    # and (optionally) compute/storage private IPs directly.
    local allowed_ips="${wg_subnet}"
    if [[ -n "$private_subnet" ]]; then
        allowed_ips="${allowed_ips}, ${private_subnet}"
    fi

    # Optional DNS push (generic, cloud-agnostic). When wg_peer_dns is set in
    # config, every peer config gets a `DNS = <value>` line so the admin
    # laptop sends DNS queries through the tunnel while it's up. Typical
    # values:
    #   • On-prem:  the customer's internal DNS server reachable on the
    #               private subnet (often the same as their LAN resolver).
    #   • AWS:      the VPC DNS resolver at <vpc-cidr-base>.2 (e.g. 10.0.0.2
    #               for a 10.0.0.0/16 VPC) — resolves Route53 private zones.
    # The resolver's IP must be inside `allowed_ips` (i.e. inside wg_subnet
    # or private_subnet) so the query actually traverses the tunnel.
    # Leave blank to keep the old behaviour (no push; laptop uses its own
    # resolver or /etc/hosts).
    local peer_dns
    peer_dns=$(cfg "wg_peer_dns")

    mkdir -p "$PEER_DIR"
    chmod 700 "$PEER_DIR"

    local n=1 octet3=0 octet4=2
    while [[ $n -le $wg_peers ]]; do
        local peer_priv peer_pub peer_psk peer_ip
        peer_priv=$(wg genkey)
        peer_pub=$(echo "$peer_priv" | wg pubkey)
        peer_psk=$(wg genpsk)
        peer_ip="${octet1}.${octet2}.${octet3}.${octet4}"

        cat >> /etc/wireguard/wg0.conf <<EOF

# peer${n}
[Peer]
PublicKey = ${peer_pub}
PresharedKey = ${peer_psk}
AllowedIPs = ${peer_ip}/32
EOF

        mkdir -p "${PEER_DIR}/peer${n}"
        # Build [Interface] block — DNS line is conditional.
        {
            echo "[Interface]"
            echo "Address = ${peer_ip}/${subnet_mask}"
            echo "PrivateKey = ${peer_priv}"
            if [[ -n "$peer_dns" ]]; then
                echo "DNS = ${peer_dns}"
            fi
            echo ""
        } > "${PEER_DIR}/peer${n}/peer${n}.conf"
        cat >> "${PEER_DIR}/peer${n}/peer${n}.conf" <<EOF
[Peer]
PublicKey = ${server_pub}
PresharedKey = ${peer_psk}
Endpoint = ${endpoint}:${wg_port}
AllowedIPs = ${allowed_ips}
PersistentKeepalive = 25
EOF

        octet4=$((octet4 + 1))
        if [[ $octet4 -gt 255 ]]; then
            octet4=0
            octet3=$((octet3 + 1))
        fi
        n=$((n + 1))
    done

    chmod 600 /etc/wireguard/wg0.conf
    chmod -R 600 "$PEER_DIR"
    find "$PEER_DIR" -type d -exec chmod 700 {} \;

    systemctl enable wg-quick@wg0
    systemctl restart wg-quick@wg0

    if ! wg show wg0 &>/dev/null; then
        log_error "Wireguard interface wg0 did not come up" \
                  "wg-quick@wg0 started but wg show fails" \
                  "Inspect logs and config" \
                  "journalctl -u wg-quick@wg0 -n 30; cat /etc/wireguard/wg0.conf"
        exit 1
    fi
    log_success "Wireguard up. Endpoint: ${endpoint}:${wg_port}"
    log_info "Peer configs at ${PEER_DIR}/peer{1..${wg_peers}}/"

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.5  Customer cert ingest + validate + install
# ─────────────────────────────────────────────────────────────────────────
# Staging convention: ssh_stage_role on the laptop copies cert files into
# ${WORK_DIR}/certs/ as one of:
#
#   wildcard.cert + wildcard.key   — ONE cert covering *.<public_domain>
#                                    (and usually the apex). Installed once to
#                                    /etc/openg2p/certs/public/<public_domain>/.
#
#   OR per-FQDN (rancher, keycloak):
#     <service>.cert + <service>.key   (PEM fullchain + key)
#     <service>.chain                  (optional separate intermediate)
#                                    Installed per hostname to
#                                    /etc/openg2p/certs/public/<hostname>/.
#
# Each install normalizes to fullchain.pem + privkey.pem (key mode 0600),
# verifies the cert/key pair, and verifies SAN/CN coverage.
# ─────────────────────────────────────────────────────────────────────────

# _rp_install_cert <src_cert> <src_key> <src_chain> <dest_dir> <covered_name...>
# Builds fullchain.pem + privkey.pem in <dest_dir>, verifies modulus match,
# and verifies the cert covers at least ONE of the <covered_name> arguments
# (each may itself be a wildcard like *.example.org).
_rp_install_cert() {
    local src_cert="$1" src_key="$2" src_chain="$3" dest="$4"; shift 4
    local -a need=("$@")

    mkdir -p "$dest"

    # Build fullchain: if cert already has ≥2 CERTIFICATE blocks it's a
    # fullchain; else concat a separate chain file when present.
    local cert_block_count
    cert_block_count=$(grep -c '^-----BEGIN CERTIFICATE-----' "$src_cert" 2>/dev/null || echo 0)
    if [[ "$cert_block_count" -ge 2 ]]; then
        cp "$src_cert" "${dest}/fullchain.pem"
    elif [[ -f "$src_chain" ]]; then
        cat "$src_cert" "$src_chain" > "${dest}/fullchain.pem"
    else
        log_warn "Cert at ${src_cert} has 1 cert block and no separate chain file."
        log_warn "Browsers will reject this unless the intermediate is supplied."
        log_warn "Proceeding with cert-only — fix the cert chain and re-run."
        cp "$src_cert" "${dest}/fullchain.pem"
    fi

    cp "$src_key" "${dest}/privkey.pem"
    chmod 0600 "${dest}/privkey.pem"
    chmod 0644 "${dest}/fullchain.pem"

    # cert/key pair must match (modulus hash)
    local cert_mod key_mod
    cert_mod=$(openssl x509 -in "${dest}/fullchain.pem" -noout -modulus 2>/dev/null | openssl md5 | awk '{print $NF}')
    key_mod=$(openssl rsa  -in "${dest}/privkey.pem"   -noout -modulus 2>/dev/null | openssl md5 | awk '{print $NF}')
    if [[ -z "$cert_mod" || -z "$key_mod" || "$cert_mod" != "$key_mod" ]]; then
        log_error "Cert/key mismatch (${dest})" \
                  "The supplied cert and key are not a matching pair" \
                  "Re-issue or re-pair the cert and key, then re-run" \
                  "openssl x509 -in ${dest}/fullchain.pem -noout -modulus | openssl md5" \
                  "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
        exit 1
    fi

    # SAN/CN must cover at least one required name. A cert SAN that is itself
    # a wildcard (*.x) covers any single-label host under x; a required name
    # that is a wildcard (*.x) matches an identical SAN exactly.
    local sans
    sans=$(openssl x509 -in "${dest}/fullchain.pem" -noout -text 2>/dev/null \
        | awk '/X509v3 Subject Alternative Name/{getline; print}' | tr ',' '\n' | sed 's/^ *DNS://' | tr -d ' ')
    local cn
    cn=$(openssl x509 -in "${dest}/fullchain.pem" -noout -subject 2>/dev/null \
        | sed -n 's/.*CN *= *\([^,]*\).*/\1/p' | tr -d ' ')

    local matches=0 want s
    for want in "${need[@]}"; do
        [[ -z "$want" ]] && continue
        while IFS= read -r s; do
            [[ -z "$s" ]] && continue
            if [[ "$s" == "$want" ]]; then matches=1; break; fi
            if [[ "$s" == "*."* && "$want" == *.${s#\*.} && "$want" != "*."* ]]; then matches=1; break; fi
        done <<< "$sans"
        [[ "$matches" == "1" ]] && break
        # CN fallback
        if [[ "$cn" == "$want" ]] || { [[ "$cn" == "*."* && "$want" == *.${cn#\*.} && "$want" != "*."* ]]; }; then
            matches=1; break
        fi
    done

    if [[ "$matches" != "1" ]]; then
        local found_sans
        found_sans=$(echo "$sans" | paste -sd' ' - 2>/dev/null)
        log_error "Cert at ${dest}/fullchain.pem does not cover: ${need[*]}" \
                  "The leaf cert's SAN/CN does not match the configured name(s). Detected on the cert → SAN: [${found_sans:-none}]  CN: [${cn:-none}]. The cert/key pair is valid, but it is issued for a different domain than configured." \
                  "Either point public_domain / *_hostname at the cert's actual domain, or supply a cert that covers ${need[*]}" \
                  "openssl x509 -in ${dest}/fullchain.pem -noout -ext subjectAltName -subject" \
                  "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
        exit 1
    fi
}

rp_install_certs() {
    local step="rp.phase1.certs"
    if skip_if_done "$step" "customer cert ingest"; then return 0; fi

    log_step "R1.5" "Ingest customer-supplied TLS certificates"

    if [[ ! -d "$STAGED_CERTS_DIR" ]]; then
        log_error "No certs staged at ${STAGED_CERTS_DIR}" \
                  "The orchestrator should have copied your cert files here" \
                  "Verify your prod-config.yaml has the tls_* paths set" \
                  "" \
                  "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
        exit 1
    fi

    mkdir -p "$CERTS_DIR"

    if [[ -f "${STAGED_CERTS_DIR}/wildcard.cert" ]]; then
        # ── Wildcard mode: one cert for *.<public_domain> ──────────────────
        local domain
        domain=$(cfg "public_domain")
        if [[ -z "$domain" ]]; then
            log_error "Wildcard cert supplied but public_domain is blank" \
                      "A wildcard cert (*.<domain>) needs public_domain set so the RP knows the base domain" \
                      "Set public_domain (e.g. prod.openg2p.org) in prod-config.yaml" \
                      "" \
                      "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
            exit 1
        fi
        _rp_install_cert \
            "${STAGED_CERTS_DIR}/wildcard.cert" \
            "${STAGED_CERTS_DIR}/wildcard.key" \
            "${STAGED_CERTS_DIR}/wildcard.chain" \
            "${CERTS_DIR}/${domain}" \
            "*.${domain}" "${domain}"
        log_success "  wildcard: *.${domain} (and ${domain}) — cert installed"
    else
        # ── Per-FQDN mode: one cert per admin hostname ─────────────────────
        local service hostname
        for service in rancher keycloak; do
            hostname=$(rp_hostname "$service")
            if [[ ! -f "${STAGED_CERTS_DIR}/${service}.cert" ]]; then
                log_error "No cert staged for ${service} (${hostname})" \
                          "Neither wildcard nor per-service cert found in ${STAGED_CERTS_DIR}" \
                          "Set tls_wildcard_cert or tls_${service}_cert in prod-config.yaml" \
                          "ls ${STAGED_CERTS_DIR}" \
                          "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
                exit 1
            fi
            _rp_install_cert \
                "${STAGED_CERTS_DIR}/${service}.cert" \
                "${STAGED_CERTS_DIR}/${service}.key" \
                "${STAGED_CERTS_DIR}/${service}.chain" \
                "${CERTS_DIR}/${hostname}" \
                "$hostname"
            log_success "  ${service}: ${hostname} — cert installed"
        done
    fi

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.6  Nginx — admin server block(s), bound to rp_private_ip:443
# ─────────────────────────────────────────────────────────────────────────
# Wildcard mode  → ONE server block: server_name <domain> *.<domain>, one cert.
# Per-FQDN mode  → one server block per admin hostname (rancher, keycloak).
# Either way every block proxies to istio_ingress and preserves the Host
# header, so Istio routes by hostname to the right backend service.
# ─────────────────────────────────────────────────────────────────────────

# _rp_emit_nginx_block <conf> <listen_ip> <server_names> <cert_dir>
_rp_emit_nginx_block() {
    local conf="$1" ip="$2" names="$3" cdir="$4"
    cat >> "$conf" <<EOF
# HTTP → HTTPS redirect for: ${names}
server {
    listen ${ip}:80;
    server_name ${names};
    return 301 https://\$host\$request_uri;
}

server {
    listen ${ip}:443 ssl;
    server_name ${names};

    ssl_certificate     ${cdir}/fullchain.pem;
    ssl_certificate_key ${cdir}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        proxy_pass                http://istio_ingress;
        proxy_http_version        1.1;
        proxy_buffering           on;
        proxy_buffers             8 16k;
        proxy_buffer_size         16k;
        proxy_busy_buffers_size   32k;
        proxy_set_header          Upgrade \$http_upgrade;
        proxy_set_header          Connection "upgrade";
        proxy_set_header          Host \$host;
        proxy_set_header          X-Real-IP \$remote_addr;
        proxy_set_header          X-Forwarded-Host \$host;
        proxy_set_header          X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header          X-Forwarded-Proto https;
        proxy_read_timeout        300s;
        proxy_send_timeout        300s;
    }
}

EOF
}

rp_setup_nginx() {
    local step="rp.phase1.nginx"
    if skip_if_done "$step" "Nginx config"; then return 0; fi

    log_step "R1.6" "Configure Nginx server blocks (admin channel, rp_private_ip)"

    local rp_private
    rp_private=$(cfg "rp_private_ip")
    [[ -z "$rp_private" ]] && rp_private=$(cfg "rp_internal_ip")   # legacy alias
    local compute_private=$(cfg "compute_private_ip")

    rm -f /etc/nginx/sites-enabled/default

    # Bound to rp_private_ip only — channel separation is enforced by the SG
    # / network firewall (only SSH + WG/UDP are open to the internet), so
    # admin services are reachable only via Wireguard or from within the
    # private/management subnet. Public env-automation server blocks (added
    # later) will bind to the same IP but on different listen ports.
    local conf=/etc/nginx/sites-available/openg2p-admin.conf
    cat > "$conf" <<EOF
# OpenG2P admin reverse proxy — managed by openg2p-prod orchestrator.
# Bound to ${rp_private}:443; reachable only via Wireguard or from within
# the internal/management network (SG / firewall blocks public 443).

upstream istio_ingress {
    server ${compute_private}:30080;
}

EOF

    if [[ -f "${STAGED_CERTS_DIR}/wildcard.cert" ]]; then
        # ── Wildcard mode: single server block for <domain> + *.<domain> ───
        local domain
        domain=$(cfg "public_domain")
        _rp_emit_nginx_block "$conf" "$rp_private" "${domain} *.${domain}" "${CERTS_DIR}/${domain}"
    else
        # ── Per-FQDN mode: one block per admin hostname ────────────────────
        local service hostname
        for service in rancher keycloak; do
            hostname=$(rp_hostname "$service")
            _rp_emit_nginx_block "$conf" "$rp_private" "$hostname" "${CERTS_DIR}/${hostname}"
        done
    fi

    ln -sf "$conf" /etc/nginx/sites-enabled/openg2p-admin.conf

    if ! nginx -t 2>&1 | tail -5; then
        log_error "nginx -t failed" \
                  "Generated config has a syntax error" \
                  "" \
                  "nginx -t" \
                  ""
        exit 1
    fi

    systemctl enable nginx
    # Full restart, not reload — reload doesn't reliably transition listen
    # sockets when the bind addresses change.
    systemctl restart nginx

    # Sanity-check the bind: nginx must actually be listening on rp_private:443
    if ! ss -tln 2>/dev/null | grep -qE "${rp_private}:443[[:space:]]"; then
        log_error "Nginx restarted but is not listening on ${rp_private}:443" \
                  "Sockets did not bind to the configured address" \
                  "Check 'ss -tlnp', cert files, and nginx error log" \
                  "ss -tlnp; journalctl -u nginx -n 30" \
                  ""
        exit 1
    fi

    log_success "Nginx serving admin hostnames on ${rp_private}:443:"
    for service in rancher keycloak; do
        log_success "  • https://$(rp_hostname "$service")"
    done

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# Phase entry
# ─────────────────────────────────────────────────────────────────────────
run_rp_phase1() {
    rp_install_basics
    rp_verify_nic
    rp_configure_ufw
    rp_setup_wireguard
    rp_install_certs
    rp_setup_nginx
}
