#!/usr/bin/env bash
# =============================================================================
# Reverse Proxy Node — Phase 1
# =============================================================================
# Two-NIC layout:
#   • vNIC-public   (rp_public_ip)   → Wireguard endpoint; future public services
#   • vNIC-internal (rp_internal_ip) → Admin Nginx server blocks
#
# Steps:
#   R1.1  apt basics
#   R1.2  Verify both NICs are bound (fail-fast with docs link otherwise)
#   R1.3  ufw — public-IP rules (SSH from admin, WG/UDP), internal trusted
#   R1.4  IP forwarding + Wireguard server (binds vNIC-public) + N peer configs
#   R1.5  Customer cert ingest + validate + install to /etc/openg2p/certs/public/
#   R1.6  Nginx — server blocks per admin hostname, bound to vNIC-internal:443
#
# Customer-supplied (NOT generated by this script):
#   • DNS A-records (admin hostnames rancher/keycloak → rp_internal_ip)
#   • TLS certificates (one wildcard OR per-FQDN)
#
# Docs:
#   https://docs.openg2p.org/operations/deployment/automation/three-node-automation#prerequisites
# =============================================================================

# Paths
CERTS_DIR="/etc/openg2p/certs/public"
PEER_DIR="/etc/wireguard/peers"
STAGED_CERTS_DIR="${WORK_DIR}/certs"      # populated by ssh_stage_role

DOCS_URL_BASE="https://docs.openg2p.org/operations/deployment/automation/three-node-automation"

# ─────────────────────────────────────────────────────────────────────────
# Helpers — resolve admin hostnames from config (auto-derive from public_domain
# when per-service field is blank)
# ─────────────────────────────────────────────────────────────────────────
rp_hostname() {
    local service="$1"   # rancher | keycloak
    local explicit
    explicit=$(cfg "${service}_hostname")
    if [[ -n "$explicit" ]]; then
        echo "$explicit"
    else
        local domain
        domain=$(cfg "public_domain")
        if [[ -z "$domain" ]]; then
            log_error "Hostname for ${service} cannot be derived" \
                      "Both ${service}_hostname and public_domain are blank in prod-config.yaml" \
                      "Set public_domain (e.g. openg2p.gov.eth) or set ${service}_hostname explicitly" \
                      "" \
                      "${DOCS_URL_BASE}#id-3.-customer-supplied-dns-records"
            exit 1
        fi
        echo "${service}.${domain}"
    fi
}

# ─────────────────────────────────────────────────────────────────────────
# R1.1  apt basics
# ─────────────────────────────────────────────────────────────────────────
rp_install_basics() {
    local step="rp.phase1.basics"
    if skip_if_done "$step" "apt basics"; then return 0; fi

    log_step "R1.1" "Install apt basics, Wireguard, Nginx"

    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y --no-install-recommends \
        curl wget jq openssl dnsutils ca-certificates \
        ufw \
        wireguard-tools \
        nginx

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.2  Verify rp_internal_ip is bound to a local NIC
# ─────────────────────────────────────────────────────────────────────────
# Note: we do NOT check rp_public_ip here. On AWS, rp_public_ip is an
# Elastic IP that AWS NATs to ENI-0's private address — the OS never sees
# the EIP itself, so `ip -4 addr` won't show it. The EIP's "boundness"
# is implicit (AWS handles NAT) and reachability is verified by SSH
# already working. We only need to ensure the OS-visible vNIC-internal
# address is up, since Nginx binds admin server blocks to it.
rp_verify_nics() {
    local step="rp.phase1.nics"
    if skip_if_done "$step" "NIC verification"; then return 0; fi

    log_step "R1.2" "Verify vNIC-internal is bound on this host"

    local pub int
    pub=$(cfg "rp_public_ip")
    int=$(cfg "rp_internal_ip")

    if [[ -z "$pub" || -z "$int" ]]; then
        log_error "rp_public_ip or rp_internal_ip not set in config" \
                  "Both fields are required" \
                  "Fill in rp_public_ip and rp_internal_ip in prod-config.yaml" \
                  "" \
                  "${DOCS_URL_BASE}#id-2.-two-network-interfaces-on-the-reverse-proxy-vm"
        exit 1
    fi

    # Public IP — do NOT check boundness. On AWS it's NAT'd EIP; on on-prem
    # dual-NIC it's bound to a NIC, but we only need to know SSH works
    # (it does, since this script is running). Log it for clarity.
    log_info "  rp_public_ip:   ${pub}   (Wireguard endpoint; NAT'd on AWS)"

    if ! ip -4 addr 2>/dev/null | grep -q "inet ${int}/"; then
        log_error "Configured rp_internal_ip ${int} is not bound to any interface" \
                  "The RP node needs a second NIC (vNIC-internal) for admin Nginx" \
                  "Attach a second vNIC to the RP VM, bind ${int}, persist via netplan" \
                  "ip -4 addr; ip route" \
                  "${DOCS_URL_BASE}#id-2.-two-network-interfaces-on-the-reverse-proxy-vm"
        exit 1
    fi

    log_success "  vNIC-internal bound: ${int}"
    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.3  ufw
# ─────────────────────────────────────────────────────────────────────────
rp_configure_ufw() {
    local step="rp.phase1.ufw"
    if skip_if_done "$step" "ufw rules"; then return 0; fi

    log_step "R1.3" "Configure ufw — public SSH/WG, internal trusted"

    local admin_cidr=$(cfg "admin_cidr" "0.0.0.0/0")
    local wg_port=$(cfg "wg_port" "51820")
    local wg_subnet=$(cfg "wg_subnet" "10.15.0.0/16")
    local private_subnet=$(cfg "private_subnet")

    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing

    # Public
    ufw allow from "$admin_cidr" to any port 22 proto tcp
    ufw allow "${wg_port}/udp" comment "Wireguard"

    # Trusted networks
    if [[ -n "$private_subnet" ]]; then
        ufw allow from "$private_subnet"
    fi
    ufw allow from "$wg_subnet"

    ufw --force enable

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.4  Wireguard server (binds vNIC-public) + peer configs
# ─────────────────────────────────────────────────────────────────────────
rp_setup_wireguard() {
    local step="rp.phase1.wireguard"
    if skip_if_done "$step" "Wireguard server"; then return 0; fi

    log_step "R1.4" "Configure Wireguard server (bound to vNIC-public)"

    local rp_pub=$(cfg "rp_public_ip")
    local endpoint=$(cfg "wg_endpoint")
    if [[ -z "$endpoint" ]]; then endpoint="$rp_pub"; fi
    local wg_subnet=$(cfg "wg_subnet" "10.15.0.0/16")
    local wg_port=$(cfg "wg_port" "51820")
    local wg_peers=$(cfg "wg_peers" "8")
    local private_subnet=$(cfg "private_subnet")

    # Enable IP forwarding (peers need to route into the internal subnet)
    sysctl -w net.ipv4.ip_forward=1 > /dev/null
    grep -q '^net.ipv4.ip_forward=1' /etc/sysctl.conf || \
        echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

    # Parse the WG /16 subnet
    local subnet_base=$(echo "$wg_subnet" | cut -d/ -f1)
    local subnet_mask=$(echo "$wg_subnet" | cut -d/ -f2)
    local octet1=$(echo "$subnet_base" | cut -d. -f1)
    local octet2=$(echo "$subnet_base" | cut -d. -f2)

    mkdir -p /etc/wireguard
    chmod 700 /etc/wireguard

    if [[ -f /etc/wireguard/wg0.conf ]] && systemctl is-active --quiet wg-quick@wg0; then
        log_success "Wireguard already configured and running."
        mark_step_done "$step"
        return 0
    fi

    local server_priv server_pub
    server_priv=$(wg genkey)
    server_pub=$(echo "$server_priv" | wg pubkey)

    local server_ip="${octet1}.${octet2}.0.1"

    # MASQUERADE matches by source CIDR (wg_subnet), not by interface name —
    # Ubuntu 24.04 uses predictable names like ens5/enp0s3.
    cat > /etc/wireguard/wg0.conf <<EOF
# OpenG2P Wireguard server — auto-generated by openg2p-prod orchestrator
[Interface]
Address = ${server_ip}/${subnet_mask}
ListenPort = ${wg_port}
PrivateKey = ${server_priv}
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s ${wg_subnet} -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s ${wg_subnet} -j MASQUERADE
EOF

    # Peer configs — admin laptops route the WG subnet AND the private subnet
    # through the tunnel, so they can reach admin services on rp_internal_ip
    # and (optionally) compute/storage private IPs directly.
    local allowed_ips="${wg_subnet}"
    if [[ -n "$private_subnet" ]]; then
        allowed_ips="${allowed_ips}, ${private_subnet}"
    fi

    # NO DNS push — customer's DNS or admin laptop's /etc/hosts handles
    # the admin hostnames. (See three-node-automation docs.)
    mkdir -p "$PEER_DIR"
    chmod 700 "$PEER_DIR"

    local n=1 octet3=0 octet4=2
    while [[ $n -le $wg_peers ]]; do
        local peer_priv peer_pub peer_psk peer_ip
        peer_priv=$(wg genkey)
        peer_pub=$(echo "$peer_priv" | wg pubkey)
        peer_psk=$(wg genpsk)
        peer_ip="${octet1}.${octet2}.${octet3}.${octet4}"

        cat >> /etc/wireguard/wg0.conf <<EOF

# peer${n}
[Peer]
PublicKey = ${peer_pub}
PresharedKey = ${peer_psk}
AllowedIPs = ${peer_ip}/32
EOF

        mkdir -p "${PEER_DIR}/peer${n}"
        cat > "${PEER_DIR}/peer${n}/peer${n}.conf" <<EOF
[Interface]
Address = ${peer_ip}/${subnet_mask}
PrivateKey = ${peer_priv}

[Peer]
PublicKey = ${server_pub}
PresharedKey = ${peer_psk}
Endpoint = ${endpoint}:${wg_port}
AllowedIPs = ${allowed_ips}
PersistentKeepalive = 25
EOF

        octet4=$((octet4 + 1))
        if [[ $octet4 -gt 255 ]]; then
            octet4=0
            octet3=$((octet3 + 1))
        fi
        n=$((n + 1))
    done

    chmod 600 /etc/wireguard/wg0.conf
    chmod -R 600 "$PEER_DIR"
    find "$PEER_DIR" -type d -exec chmod 700 {} \;

    systemctl enable wg-quick@wg0
    systemctl restart wg-quick@wg0

    if ! wg show wg0 &>/dev/null; then
        log_error "Wireguard interface wg0 did not come up" \
                  "wg-quick@wg0 started but wg show fails" \
                  "Inspect logs and config" \
                  "journalctl -u wg-quick@wg0 -n 30; cat /etc/wireguard/wg0.conf"
        exit 1
    fi
    log_success "Wireguard up. Endpoint: ${endpoint}:${wg_port}"
    log_info "Peer configs at ${PEER_DIR}/peer{1..${wg_peers}}/"

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.5  Customer cert ingest + validate + install
# ─────────────────────────────────────────────────────────────────────────
# Staging convention: ssh_stage_role on the laptop copies cert files into
# ${WORK_DIR}/certs/ as one of:
#
#   wildcard.cert + wildcard.key   — ONE cert covering *.<public_domain>
#                                    (and usually the apex). Installed once to
#                                    /etc/openg2p/certs/public/<public_domain>/.
#
#   OR per-FQDN (rancher, keycloak):
#     <service>.cert + <service>.key   (PEM fullchain + key)
#     <service>.chain                  (optional separate intermediate)
#                                    Installed per hostname to
#                                    /etc/openg2p/certs/public/<hostname>/.
#
# Each install normalizes to fullchain.pem + privkey.pem (key mode 0600),
# verifies the cert/key pair, and verifies SAN/CN coverage.
# ─────────────────────────────────────────────────────────────────────────

# _rp_install_cert <src_cert> <src_key> <src_chain> <dest_dir> <covered_name...>
# Builds fullchain.pem + privkey.pem in <dest_dir>, verifies modulus match,
# and verifies the cert covers at least ONE of the <covered_name> arguments
# (each may itself be a wildcard like *.example.org).
_rp_install_cert() {
    local src_cert="$1" src_key="$2" src_chain="$3" dest="$4"; shift 4
    local -a need=("$@")

    mkdir -p "$dest"

    # Build fullchain: if cert already has ≥2 CERTIFICATE blocks it's a
    # fullchain; else concat a separate chain file when present.
    local cert_block_count
    cert_block_count=$(grep -c '^-----BEGIN CERTIFICATE-----' "$src_cert" 2>/dev/null || echo 0)
    if [[ "$cert_block_count" -ge 2 ]]; then
        cp "$src_cert" "${dest}/fullchain.pem"
    elif [[ -f "$src_chain" ]]; then
        cat "$src_cert" "$src_chain" > "${dest}/fullchain.pem"
    else
        log_warn "Cert at ${src_cert} has 1 cert block and no separate chain file."
        log_warn "Browsers will reject this unless the intermediate is supplied."
        log_warn "Proceeding with cert-only — fix the cert chain and re-run."
        cp "$src_cert" "${dest}/fullchain.pem"
    fi

    cp "$src_key" "${dest}/privkey.pem"
    chmod 0600 "${dest}/privkey.pem"
    chmod 0644 "${dest}/fullchain.pem"

    # cert/key pair must match (modulus hash)
    local cert_mod key_mod
    cert_mod=$(openssl x509 -in "${dest}/fullchain.pem" -noout -modulus 2>/dev/null | openssl md5 | awk '{print $NF}')
    key_mod=$(openssl rsa  -in "${dest}/privkey.pem"   -noout -modulus 2>/dev/null | openssl md5 | awk '{print $NF}')
    if [[ -z "$cert_mod" || -z "$key_mod" || "$cert_mod" != "$key_mod" ]]; then
        log_error "Cert/key mismatch (${dest})" \
                  "The supplied cert and key are not a matching pair" \
                  "Re-issue or re-pair the cert and key, then re-run" \
                  "openssl x509 -in ${dest}/fullchain.pem -noout -modulus | openssl md5" \
                  "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
        exit 1
    fi

    # SAN/CN must cover at least one required name. A cert SAN that is itself
    # a wildcard (*.x) covers any single-label host under x; a required name
    # that is a wildcard (*.x) matches an identical SAN exactly.
    local sans
    sans=$(openssl x509 -in "${dest}/fullchain.pem" -noout -text 2>/dev/null \
        | awk '/X509v3 Subject Alternative Name/{getline; print}' | tr ',' '\n' | sed 's/^ *DNS://' | tr -d ' ')
    local cn
    cn=$(openssl x509 -in "${dest}/fullchain.pem" -noout -subject 2>/dev/null \
        | sed -n 's/.*CN *= *\([^,]*\).*/\1/p' | tr -d ' ')

    local matches=0 want s
    for want in "${need[@]}"; do
        [[ -z "$want" ]] && continue
        while IFS= read -r s; do
            [[ -z "$s" ]] && continue
            if [[ "$s" == "$want" ]]; then matches=1; break; fi
            if [[ "$s" == "*."* && "$want" == *.${s#\*.} && "$want" != "*."* ]]; then matches=1; break; fi
        done <<< "$sans"
        [[ "$matches" == "1" ]] && break
        # CN fallback
        if [[ "$cn" == "$want" ]] || { [[ "$cn" == "*."* && "$want" == *.${cn#\*.} && "$want" != "*."* ]]; }; then
            matches=1; break
        fi
    done

    if [[ "$matches" != "1" ]]; then
        log_error "Cert at ${dest}/fullchain.pem does not cover: ${need[*]}" \
                  "The supplied cert's SAN/CN does not match the configured name(s)" \
                  "Issue a cert covering ${need[*]}, or change public_domain / *_hostname to match the cert" \
                  "openssl x509 -in ${dest}/fullchain.pem -noout -text | grep -A1 'Subject Alternative Name'" \
                  "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
        exit 1
    fi
}

rp_install_certs() {
    local step="rp.phase1.certs"
    if skip_if_done "$step" "customer cert ingest"; then return 0; fi

    log_step "R1.5" "Ingest customer-supplied TLS certificates"

    if [[ ! -d "$STAGED_CERTS_DIR" ]]; then
        log_error "No certs staged at ${STAGED_CERTS_DIR}" \
                  "The orchestrator should have copied your cert files here" \
                  "Verify your prod-config.yaml has the tls_* paths set" \
                  "" \
                  "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
        exit 1
    fi

    mkdir -p "$CERTS_DIR"

    if [[ -f "${STAGED_CERTS_DIR}/wildcard.cert" ]]; then
        # ── Wildcard mode: one cert for *.<public_domain> ──────────────────
        local domain
        domain=$(cfg "public_domain")
        if [[ -z "$domain" ]]; then
            log_error "Wildcard cert supplied but public_domain is blank" \
                      "A wildcard cert (*.<domain>) needs public_domain set so the RP knows the base domain" \
                      "Set public_domain (e.g. prod.openg2p.org) in prod-config.yaml" \
                      "" \
                      "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
            exit 1
        fi
        _rp_install_cert \
            "${STAGED_CERTS_DIR}/wildcard.cert" \
            "${STAGED_CERTS_DIR}/wildcard.key" \
            "${STAGED_CERTS_DIR}/wildcard.chain" \
            "${CERTS_DIR}/${domain}" \
            "*.${domain}" "${domain}"
        log_success "  wildcard: *.${domain} (and ${domain}) — cert installed"
    else
        # ── Per-FQDN mode: one cert per admin hostname ─────────────────────
        local service hostname
        for service in rancher keycloak; do
            hostname=$(rp_hostname "$service")
            if [[ ! -f "${STAGED_CERTS_DIR}/${service}.cert" ]]; then
                log_error "No cert staged for ${service} (${hostname})" \
                          "Neither wildcard nor per-service cert found in ${STAGED_CERTS_DIR}" \
                          "Set tls_wildcard_cert or tls_${service}_cert in prod-config.yaml" \
                          "ls ${STAGED_CERTS_DIR}" \
                          "${DOCS_URL_BASE}#id-4.-customer-supplied-tls-certificates"
                exit 1
            fi
            _rp_install_cert \
                "${STAGED_CERTS_DIR}/${service}.cert" \
                "${STAGED_CERTS_DIR}/${service}.key" \
                "${STAGED_CERTS_DIR}/${service}.chain" \
                "${CERTS_DIR}/${hostname}" \
                "$hostname"
            log_success "  ${service}: ${hostname} — cert installed"
        done
    fi

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.6  Nginx — admin server block(s), vNIC-internal:443
# ─────────────────────────────────────────────────────────────────────────
# Wildcard mode  → ONE server block: server_name <domain> *.<domain>, one cert.
# Per-FQDN mode  → one server block per admin hostname (rancher, keycloak).
# Either way every block proxies to istio_ingress and preserves the Host
# header, so Istio routes by hostname to the right backend service.
# ─────────────────────────────────────────────────────────────────────────

# _rp_emit_nginx_block <conf> <listen_ip> <server_names> <cert_dir>
_rp_emit_nginx_block() {
    local conf="$1" ip="$2" names="$3" cdir="$4"
    cat >> "$conf" <<EOF
# HTTP → HTTPS redirect for: ${names}
server {
    listen ${ip}:80;
    server_name ${names};
    return 301 https://\$host\$request_uri;
}

server {
    listen ${ip}:443 ssl;
    server_name ${names};

    ssl_certificate     ${cdir}/fullchain.pem;
    ssl_certificate_key ${cdir}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        proxy_pass                http://istio_ingress;
        proxy_http_version        1.1;
        proxy_buffering           on;
        proxy_buffers             8 16k;
        proxy_buffer_size         16k;
        proxy_busy_buffers_size   32k;
        proxy_set_header          Upgrade \$http_upgrade;
        proxy_set_header          Connection "upgrade";
        proxy_set_header          Host \$host;
        proxy_set_header          X-Real-IP \$remote_addr;
        proxy_set_header          X-Forwarded-Host \$host;
        proxy_set_header          X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header          X-Forwarded-Proto https;
        proxy_read_timeout        300s;
        proxy_send_timeout        300s;
    }
}

EOF
}

rp_setup_nginx() {
    local step="rp.phase1.nginx"
    if skip_if_done "$step" "Nginx config"; then return 0; fi

    log_step "R1.6" "Configure Nginx server blocks (admin channel, vNIC-internal)"

    local rp_internal=$(cfg "rp_internal_ip")
    local compute_private=$(cfg "compute_private_ip")

    rm -f /etc/nginx/sites-enabled/default

    # Bound to the internal IP only. Public (env automation) server blocks
    # will be added later, bound to rp_public_ip.
    local conf=/etc/nginx/sites-available/openg2p-admin.conf
    cat > "$conf" <<EOF
# OpenG2P admin reverse proxy — managed by openg2p-prod orchestrator.
# Bound to vNIC-internal (${rp_internal}); reachable only via Wireguard or
# from within the internal/management network.

upstream istio_ingress {
    server ${compute_private}:30080;
}

EOF

    if [[ -f "${STAGED_CERTS_DIR}/wildcard.cert" ]]; then
        # ── Wildcard mode: single server block for <domain> + *.<domain> ───
        local domain
        domain=$(cfg "public_domain")
        _rp_emit_nginx_block "$conf" "$rp_internal" "${domain} *.${domain}" "${CERTS_DIR}/${domain}"
    else
        # ── Per-FQDN mode: one block per admin hostname ────────────────────
        local service hostname
        for service in rancher keycloak; do
            hostname=$(rp_hostname "$service")
            _rp_emit_nginx_block "$conf" "$rp_internal" "$hostname" "${CERTS_DIR}/${hostname}"
        done
    fi

    ln -sf "$conf" /etc/nginx/sites-enabled/openg2p-admin.conf

    if ! nginx -t 2>&1 | tail -5; then
        log_error "nginx -t failed" \
                  "Generated config has a syntax error" \
                  "" \
                  "nginx -t" \
                  ""
        exit 1
    fi

    systemctl enable nginx
    # Full restart, not reload — reload doesn't reliably transition listen
    # sockets when the bind addresses change.
    systemctl restart nginx

    # Sanity-check the bind: nginx must actually be listening on rp_internal:443
    if ! ss -tln 2>/dev/null | grep -qE "${rp_internal}:443[[:space:]]"; then
        log_error "Nginx restarted but is not listening on ${rp_internal}:443" \
                  "Sockets did not bind to the configured address" \
                  "Check 'ss -tlnp', cert files, and nginx error log" \
                  "ss -tlnp; journalctl -u nginx -n 30" \
                  ""
        exit 1
    fi

    log_success "Nginx serving admin hostnames on ${rp_internal}:443:"
    for service in rancher keycloak; do
        log_success "  • https://$(rp_hostname "$service")"
    done

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# Phase entry
# ─────────────────────────────────────────────────────────────────────────
run_rp_phase1() {
    rp_install_basics
    rp_verify_nics
    rp_configure_ufw
    rp_setup_wireguard
    rp_install_certs
    rp_setup_nginx
}
