apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: keycloak
spec:
  selector:
    istio-keycloak: ingressgateway
  servers:
  - hosts:
    - ${KEYCLOAK_HOSTNAME}
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - ${KEYCLOAK_HOSTNAME}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: tls-keycloak-ingress
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
spec:
  gateways:
  - keycloak
  hosts:
  - ${KEYCLOAK_HOSTNAME}
  http:
  - route:
    - destination:
        host: keycloak
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https
