apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - ${KEYCLOAK_HOSTNAME}
  http:
    - route:
        - destination:
            host: keycloak
            port:
              number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https
