apiVersion: v2
name: keymanager
description: A Helm chart for MOSIP Keymanager module
type: application
version: 12.0.1-B3
appVersion: ""
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
  condition: postgresql.enabled
- name: softhsm
  repository: https://mosip.github.io/mosip-helm
  version: 12.0.1-B2
  condition: softhsm.enabled
- name: artifactory
  repository: https://mosip.github.io/mosip-helm
  version: 12.0.2
  condition: artifactory.enabled
keywords:
  - mosip
  - keymanager
  - kernel
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "Keymanager"
