apiVersion: v2
name: keymanager
description: A Helm chart for MOSIP Keymanager module
type: application
version: 12.1.0
appVersion: "12.1.0"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
keywords:
  - mosip
  - keymanager
  - kernel
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "Keymanager"
