envs:
  config:
    SERVER_maxHttpHeaderSize: "200000"
    KAFKA_CLUSTERS_0_NAME: main
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://debezium-service.reporting:8083
    KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
    KAFKA_CLUSTERS_0_KAFKACONNECT_1_ADDRESS: http://es-connect.reporting:8083
    KAFKA_CLUSTERS_0_KAFKACONNECT_1_NAME: es-connect
    KAFKA_CLUSTERS_1_NAME: ml
    KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka.ml:9092
image:
  pullPolicy: Always
