logRetentionHours: "2"
defaultReplicationFactor: 1
offsetsTopicReplicationFactor: 1
transactionStateLogReplicationFactor: 1
numPartitions: 5
autoCreateTopicsEnable: true
deleteTopicEnable: true

replicaCount: 1

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 8Gi

zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi

kraft:
  enabled: false

resources:
  limits: {}
  requests:
    cpu: 200m
    memory: 1500Mi