extraConfig: |-
  log.retention.hours=2
  default.replication.factor=1
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1
  auto.create.topics.enable=true
  delete.topic.enable=true
  num.partitions=5

controller:
  resources:
    limits: {}
    requests:
      cpu: 200m
      memory: 1500Mi

broker:
  persistence:
    enabled: false

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
