{{- if .Values.springConfig.gitRepo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-git-config-secret
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- range $k, $v := (omit .Values.springConfig.gitRepo "enabled" "envVars") }}
  {{ $k }}: {{ include "common.tplvalues.render" (dict "value" $v "context" $) | b64enc | quote }}
  {{- end }}
{{- end }}
