apiVersion: v2
name: esignet
description: A Helm chart for MOSIP eSignet module
type: application
version: 1.4.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: oidc-ui
  version: 1.4.0
  condition: oidc-ui.enabled
- name: mock-identity-system
  version: 0.9.2
  condition: mock-identity-system.enabled
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
  condition: postgresql.enabled
- name: softhsm
  repository: https://mosip.github.io/mosip-helm
  version: 12.0.1-B2
  condition: softhsm.enabled
- name: artifactory
  repository: https://mosip.github.io/mosip-helm
  version: 12.0.2
  condition: artifactory.enabled
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.x.x
  condition: redis.enabled
- name: kafka
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 29.x.x
  condition: kafka.enabled
home: https://mosip.io
keywords:
  - mosip
  - esignet
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "eSignet"
