{{- if and .Values.keygen.enabled .Values.keygen.startUpCommand }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-keygen
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.keygen.startUpCommand }}
  startup-command-sh: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.keygen.startUpCommand "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
