apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: internal
  namespace: ${NS}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - ${WILDCARD_HOSTNAME}
    port:
      name: http-redirect-https
      number: 81
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - ${WILDCARD_HOSTNAME}
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public
  namespace: ${NS}
spec:
  selector:
    istio: ingressgateway-public
  servers:
  - hosts:
    - ${WILDCARD_HOSTNAME}
    port:
      name: http-redirect-https
      number: 81
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - ${WILDCARD_HOSTNAME}
    port:
      name: http
      number: 80
      protocol: HTTP
