apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: primary
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    pathNormalization:
      normalization: MERGE_SLASHES
    defaultConfig:
      proxyMetadata:
        ISTIO_META_IDLE_TIMEOUT: 0s
      holdApplicationUntilProxyStarts: true
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
