apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: internal
  namespace: ${NS}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "${WILDCARD_HOSTNAME}"
    port:
      name: http2
      number: 8080
      protocol: HTTP2
    tls:
      httpsRedirect: true
  - hosts:
    - "${WILDCARD_HOSTNAME}"
    port:
      name: https
      number: 8443
      protocol: HTTPS
    tls:
      credentialName: tls-openg2p-${NS}-ingress
      mode: SIMPLE
