persistence:
  enabled: true
  size: 16Gi

extraEnvVars:
- name: MINIO_IDENTITY_OPENID_CONFIG_URL
  value: "http://keycloak.keycloak/realms/${REALM_NAME}/.well-known/openid-configuration"
- name: MINIO_IDENTITY_OPENID_CLIENT_ID
  value: "minio-auth-client"
- name: MINIO_IDENTITY_OPENID_DISPLAY_NAME
  value: Keycloak
- name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
  value: "${MINIO_AUTH_CLIENT_SECRET}"
- name: MINIO_IDENTITY_OPENID_CLAIM_NAME
  value: groups
- name: MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC
  value: "on"
- name: MINIO_IDENTITY_OPENID_CLAIM_USERINFO
  value: "http://keycloak.keycloak/realms/${REALM_NAME}/protocol/openid-connect/userinfo"
