apiVersion: v2
name: artifactory
description: A Helm chart for MOSIP Artifactory
type: application
version: 12.0.2
appVersion: ""
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.x.x
home: https://mosip.io
keywords:
  - artifactory
  - antivirus
  - anti-virus
maintainers:
  - email: info@mosip.io
    name: MOSIP
