apiVersion: v2
name: mimoto
description: A Helm chart for Mimoto (Inji Backend)
type: application
version: 0.13.1
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: artifactory
  version: 12.0.2
  condition: artifactory.enabled
keywords:
  - mosip
  - mimoto
  - kernel
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "Mimoto"
