apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.json.template: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.configJsonTemplate "context" $) | nindent 4 }}
  start-enketo.sh: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.startEnketoScript "context" $) | nindent 4 }}
