apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  enketo-secret: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "enketo-secret" "length" 64 "providedValues" (list "enketoSecret") "context" $) }}
  enketo-less-secret: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "enketo-less-secret" "length" 32 "providedValues" (list "enketoLessSecret") "context" $) }}
  enketo-api-key: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "enketo-api-key" "length" 128 "providedValues" (list "enketoLessSecret") "context" $) }}
