apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
data:
  odk.conf.template: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.odkConfTemplate "context" $) | nindent 4 }}
  setup-odk.sh: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.setupOdkScript "context" $) | nindent 4 }}
