# Ports to be opened for Kubernetes cluster. See deployment documentation at http://docs.openg2p.org 
- hosts: cluster
  become: true
  tasks:
    - community.general.ufw:
        rule: allow
        name: OpenSSH
    
    - community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - community.general.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Postgres
      community.general.ufw:
        rule: allow
        port: 5432 
        proto: tcp

    - name: RKE2 
      community.general.ufw:
        rule: allow
        port: 9345
        proto: tcp

    - name: RKE2 
      community.general.ufw:
        rule: allow
        port: 10250
        proto: tcp
    
    - name: Allow port range 2379-2380 for Rancher
      community.general.ufw:
        rule: allow
        port: 2379:2380
        proto: tcp

    - name: Kubernetes nodeports
      community.general.ufw:
        rule: allow
        port: 30000:32767   
        proto: tcp

    - name: Flannel
      community.general.ufw:
        rule: allow
        port: 8472
        proto: udp

    - name: Kubernetes API
      community.general.ufw:
        rule: allow
        port: 6443
        proto: tcp

    - name: Prometheus metrics
      community.general.ufw:
        rule: allow
        port: 9796
        proto: tcp

    - community.general.ufw:
        state: enabled


