{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-frontend
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  odk.conf.template: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.frontend.odkConfTemplate "context" $) | nindent 4 }}
  client-config.json.template: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.frontend.clientConfigJsonTemplate "context" $) | nindent 4 }}
  setup-odk.sh: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.frontend.setupOdkScript "context" $) | nindent 4 }}
{{- end }}
