{{- if .Values.ingress.enabled }}
{{- $ingressHostname := include "common.tplvalues.render" (dict "value" .Values.ingress.hostname "context" $) }}
{{- $mainHostname := include "common.tplvalues.render" (dict "value" .Values.hostname "context" $) }}
{{- $hostname := default $mainHostname $ingressHostname }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ include "common.tplvalues.render" (dict "value" .Values.ingress.ingressClassName "context" $) | quote }}
  {{- end }}
  rules:
    {{- if $hostname }}
    - host: {{ $hostname | quote }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ include "common.tplvalues.render" (dict "value" .Values.ingress.path "context" $) }}
            {{- if .Values.ingress.pathType }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.tplvalues.render" (dict "value" .Values.ingress.backendServiceName "context" $)) "servicePort" "http" "context" $) | nindent 14 }}
    {{- if .Values.ingress.extraRules }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.extraRules "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
      {{- if .Values.ingress.tlsSecret }}
    - secretName: {{ include "common.tplvalues.render" (dict "value" .Values.ingress.tlsSecret "context" $) }}
      {{- else }}
    - secretName: {{ $hostname }}-tls
      {{- end }}
      {{- if $hostname }}
      hosts:
        - {{ $hostname | quote }}
      {{- end }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
