global:
  # hostname name of installation
  odkHostname: "odk.openg2p.sandbox.net"
  # system admin email
  sysAdminEmail: "admin@odk.openg2p.sandbox.net"

  keycloakBaseUrl: https://keycloak.your.org
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

odk-central-mail:
  enabled: true
  mailname: "openg2p.sandbox.net"
odk-central-pyxform:
  enabled: true
odk-central-enketo:
  enabled: true
odk-central-backend:
  enabled: true
  envVars:
    OIDC_ISSUER_URL: '{{ tpl .Values.global.keycloakIssuerUrl $ }}'
    OIDC_CLIENT_ID: ''
    OIDC_CLIENT_SECRET: ''
  postgresql:
    nameOverride: odk-central-postgresql
odk-central-frontend:
  enabled: true
