apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ml-ttk
  namespace: ml
spec:
  gateways:
  - istio-system/all-hosts
  hosts:
  - ${ML_TTK_HOSTNAME}
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: ml-ttk-ml-testing-toolkit-backend
        port:
          number: 5050
  - match:
    - uri:
        prefix: /socket.io
    route:
    - destination:
        host: ml-ttk-ml-testing-toolkit-backend
        port:
          number: 5050
  - match:
    - uri:
        prefix: /mojaloop
    route:
    - destination:
        host: ml-ttk-ml-testing-toolkit-backend
        port:
          number: 4040
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ml-ttk-ml-testing-toolkit-frontend
        port:
          number: 6060
