extraConfig: |-
  log.retention.hours=2
  default.replication.factor=1
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1
  auto.create.topics.enable=true
  delete.topic.enable=true

controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi

broker:
  persistence:
    enabled: false

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
