central:
  centralledger:
    mysql:
      persistence:
        enabled: true
        size: 1Gi
    kafka:
      persistence:
        enabled: true
        size: 1Gi
      zookeeper:
        persistence:
          enabled: true
          size: 1Gi
    centralledger-handler-transfer-prepare:
      config:
        enable_on_us_transfers: true
  enabled: true

ml-api-adapter:
  enabled: true

emailnotifier:
  enabled: false

account-lookup-service:
  enabled: true
  mysql:
    persistence:
      enabled: true
      size: 1Gi

quoting-service:
  enabled: true

transaction-requests-service:
  enabled: true

thirdparty:
  enabled: false

simulator:
  enabled: false

mojaloop-simulator:
  enabled: false

mojaloop-ttk-simulators:
  enabled: false

mojaloop-bulk:
  enabled: false

ml-testing-toolkit:
  enabled: false

ml-ttk-posthook-setup:
  postInstallHook:
    enabled: false

ml-ttk-posthook-tests:
  postInstallHook:
    enabled: false

ml-ttk-cronjob-tests:
  scheduling:
    enabled: false

ml-ttk-test-setup:
  enabled: false

ml-ttk-test-val-gp:
  tests:
    enabled: false

ml-ttk-test-val-bulk:
  tests:
    enabled: false

ml-ttk-test-setup-tp:
  tests:
    enabled: false

ml-ttk-test-val-tp:
  tests:
    enabled: false

ml-ttk-test-setup-sdk-bulk:
  tests:
    enabled: false

ml-ttk-test-val-sdk-bulk:
  tests:
    enabled: false
