primary:
  persistence:
    size: 1Gi

auth:
  username: randomuser

initdbScripts:
  init_ml_dbs.sh: |-
    #!/bin/bash
    echo "create database if not exists account_lookup;" | mysql -u"root" -p"$MYSQL_ROOT_PASSWORD" 
    echo "create database if not exists central_ledger;" | mysql -u"root" -p"$MYSQL_ROOT_PASSWORD"
    echo "create user if not exists 'account_lookup'@'%' identified by '${MYSQL_PASSWORD}';" | mysql -u"root" -p"$MYSQL_ROOT_PASSWORD"
    echo "create user if not exists 'central_ledger'@'%' identified by '${MYSQL_PASSWORD}';" | mysql -u"root" -p"$MYSQL_ROOT_PASSWORD"
    echo "grant ALL PRIVILEGES on account_lookup .* to 'account_lookup'@'%' with grant option;" | mysql -u"root" -p"$MYSQL_ROOT_PASSWORD"
    echo "grant ALL PRIVILEGES on central_ledger .* to 'central_ledger'@'%' with grant option;" | mysql -u"root" -p"$MYSQL_ROOT_PASSWORD"
